case_name: pazy_krylov_ROM
linss_path: \home\maxal\Aircraft-Aeroelastic-Control-Benchmark\TestBenchPazy\sim_setup\pazy_krylov_ROM\coupled_full\20260531\from_sharpy\pazy_krylov_ROM.linss.h5
created: 2026-05-31
body_case: coupled_full
note: Open-loop export. Fill deflection later for closed-loop HIL.
